# Generated by Django 3.1.2 on 2020-11-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewarticle',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewarticle',
            name='unlikecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='talkarticle',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
