# Generated by Django 3.1.2 on 2020-11-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201120_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewarticle',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
