# Generated by Django 3.1.2 on 2020-11-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201119_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='talkarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
    ]
