# Generated by Django 3.1.2 on 2020-11-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='text_nickname', max_length=100),
            preserve_default=False,
        ),
    ]
