# Generated by Django 3.1.2 on 2020-11-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201125_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre_prefer1',
            field=models.IntegerField(choices=[(28, '액션'), (12, '모험'), (16, '애니메이션'), (35, '코미디'), (80, '범죄'), (99, '다큐멘터리'), (18, '드라마'), (10751, '가족'), (14, '판타지'), (36, '역사'), (27, '공포'), (10402, '음악'), (9648, '미스터리'), (10749, '로맨스'), (878, 'Sf'), (10770, 'Tv영화'), (53, '스릴러'), (10752, '전쟁'), (37, '서부')], null=True, verbose_name='선호장르1 *'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre_prefer2',
            field=models.IntegerField(choices=[(28, '액션'), (12, '모험'), (16, '애니메이션'), (35, '코미디'), (80, '범죄'), (99, '다큐멘터리'), (18, '드라마'), (10751, '가족'), (14, '판타지'), (36, '역사'), (27, '공포'), (10402, '음악'), (9648, '미스터리'), (10749, '로맨스'), (878, 'Sf'), (10770, 'Tv영화'), (53, '스릴러'), (10752, '전쟁'), (37, '서부')], null=True, verbose_name='선호장르2 *'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre_prefer3',
            field=models.IntegerField(choices=[(28, '액션'), (12, '모험'), (16, '애니메이션'), (35, '코미디'), (80, '범죄'), (99, '다큐멘터리'), (18, '드라마'), (10751, '가족'), (14, '판타지'), (36, '역사'), (27, '공포'), (10402, '음악'), (9648, '미스터리'), (10749, '로맨스'), (878, 'Sf'), (10770, 'Tv영화'), (53, '스릴러'), (10752, '전쟁'), (37, '서부')], null=True, verbose_name='선호장르3 *'),
        ),
    ]
