# Generated by Django 3.1.2 on 2020-11-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201120_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField()),
                ('vote_count', models.IntegerField()),
                ('video', models.BooleanField()),
                ('poster_path', models.TextField()),
                ('movie_id', models.IntegerField()),
                ('original_language', models.TextField()),
                ('original_title', models.TextField()),
                ('genre_ids', models.TextField()),
                ('title', models.TextField()),
                ('vote_average', models.IntegerField()),
                ('overview', models.TextField()),
                ('release_date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSimilarMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField()),
                ('vote_count', models.IntegerField()),
                ('video', models.BooleanField()),
                ('poster_path', models.TextField()),
                ('movie_id', models.IntegerField()),
                ('original_language', models.TextField()),
                ('original_title', models.TextField()),
                ('genre_ids', models.TextField()),
                ('title', models.TextField()),
                ('vote_average', models.IntegerField()),
                ('overview', models.TextField()),
                ('release_date', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favoritemovie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userfavoritemovie'),
        ),
        migrations.AddField(
            model_name='user',
            name='similarmovie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usersimilarmovie'),
        ),
    ]
