# Generated by Django 3.1.2 on 2020-11-20 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201121_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favoritemovie',
        ),
        migrations.RemoveField(
            model_name='user',
            name='similarmovie',
        ),
        migrations.AddField(
            model_name='userfavoritemovie',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersimilarmovie',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
