# Generated by Django 3.1.2 on 2020-11-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201124_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='selfpr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
