# Generated by Django 3.1.2 on 2020-11-25 10:06

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201125_1906'),
        ('accounts', '0005_auto_20201125_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dibs_movies',
            field=models.ManyToManyField(blank=True, related_name='dibs_users', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre_prefer1',
            field=models.IntegerField(choices=[(28, '액션'), (12, '모험'), (16, '애니메이션'), (35, '코미디'), (80, '범죄'), (99, '다큐멘터리'), (18, '드라마'), (10751, '가족'), (14, '판타지'), (36, '역사'), (27, '공포'), (10402, '음악'), (9648, '미스터리'), (10749, '로맨스'), (878, 'Sf'), (10770, 'Tv영화'), (53, '스릴러'), (10752, '전쟁'), (37, '서부')], verbose_name='선호장르1 *'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre_prefer2',
            field=models.IntegerField(choices=[(28, '액션'), (12, '모험'), (16, '애니메이션'), (35, '코미디'), (80, '범죄'), (99, '다큐멘터리'), (18, '드라마'), (10751, '가족'), (14, '판타지'), (36, '역사'), (27, '공포'), (10402, '음악'), (9648, '미스터리'), (10749, '로맨스'), (878, 'Sf'), (10770, 'Tv영화'), (53, '스릴러'), (10752, '전쟁'), (37, '서부')], verbose_name='선호장르2 *'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre_prefer3',
            field=models.IntegerField(choices=[(28, '액션'), (12, '모험'), (16, '애니메이션'), (35, '코미디'), (80, '범죄'), (99, '다큐멘터리'), (18, '드라마'), (10751, '가족'), (14, '판타지'), (36, '역사'), (27, '공포'), (10402, '음악'), (9648, '미스터리'), (10749, '로맨스'), (878, 'Sf'), (10770, 'Tv영화'), (53, '스릴러'), (10752, '전쟁'), (37, '서부')], verbose_name='선호장르3 *'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='%Y/%m/%d', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='selfpr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='자기소개'),
        ),
    ]
