# Generated by Django 3.1.2 on 2020-11-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='content',
            field=models.CharField(max_length=100, verbose_name='댓글내용'),
        ),
    ]
