# Generated by Django 3.1.2 on 2020-11-22 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201122_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscore',
            old_name='movie_id',
            new_name='movie_origin_id',
        ),
        migrations.AddField(
            model_name='userscore',
            name='movie',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
    ]
